### ISSUE TITLE
Implement binary systems in visualizations

### ISSUE THREAD

**Issue by hannorein** [OpenExoplanetCatalogue/oec_web#6]
As suggested by by @Sol-d

**Comment by ziphead** [comment]
@hannorein 
Working on this issue, I found one strange thing. 
Here is a screenshot from OEC website. Habitable zone visualisation shows that Alpha Centauri B c is in habitable zone, but its description doesn't say anything about it. (Proxima Centauri doesn't show up)
![screenshot from 2017-01-25 03 22 43](https://cloud.githubusercontent.com/assets/12198067/22262902/9ebd5d46-e2ad-11e6-9e07-2871c3f5d383.png)

And my implementation of binary visualisation shows that Proxima Centauri is not in the Habitable zone. Which is odd, because [Wikipedia says this](https://en.wikipedia.org/wiki/Proxima_Centauri_b). So I've confused: Is it formulas or I made a mistake somewhere?
![screenshot from 2017-01-25 03 36 22](https://cloud.githubusercontent.com/assets/12198067/22263674/34f340b2-e2b0-11e6-8018-23863211e674.png)

Other habitable zone planets(P-type) in binary systems seem to be fine from the first glance. Just want to make sure before I push this update.

**Comment by ziphead** [comment]
The OEC formula calculates luminosity = pow(stellarMass,4.). For Proxima Centauri it's 0.12^4 = 0.00020736
Wikipedia links to a [research](https://en.wikipedia.org/wiki/Proxima_Centauri_b#cite_note-nature_paper-1) where they measured luminosity, as 0.0015 L☉.   Luminosity value is a part of habitable zone formula, so I guess this is why we have Proxima Centauri b out of the green ring.

**Comment by ziphead** [comment]
@hannorein So leave it as it is, or what?

**Comment by hannorein** [comment]
For now. Yes.

**Comment by ziphead** [comment]
Ok, i'm off then
